#!/usr/bin/env bash
#case example
num=0
while [ $num -le 20 ]
do
    echo $num
    case $num in
        4 ) echo "bad luck from China" ;;
        9 ) echo "bad luck from Japan" ;;
        17 ) echo "bad luck from Italy" ;;
    esac
    ((num++))
done
