#!/usr/bin/env bash
#Gives info on the file school
SC="school"

if [ -e "$FILE" ]
then
    echo "school file exists"
    if [ ! -s "$SC" ]
    then
        echo "school file is empty"
    else
        echo "school file is not empty"
    fi
    if [ -f "$SC" ]
    then
        echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi
